spring.application.name=WeatherSpot

visualcrossing.api-key-1=${VISUALCROSSING_API_KEY_1}
visualcrossing.api-key-2=${VISUALCROSSING_API_KEY_2}
visualcrossing.api-key-3=${VISUALCROSSING_API_KEY_3}

location.api-key=${LOCATION_API_KEY}